@startuml Ex_04_Assignment
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945992]]

title Example 4. Assignment (Relationships)

Business_Collaboration(BC_1, "Finance\n(business collaboration)")
Business_Function(BF_5, "Transaction Processing\n(business function)")
Business_Interface(BIf_1, "Payment Interface\n(business interface)")
Business_Service(BS_2, "Payment Service\n(business service)")
Rel_Assignment_Right(BIf_1, BS_2, "assigned to")
Rel_Assignment_Right(BC_1, BF_5, "assigned to")
Rel_Composition_Down(BC_1, BIf_1, "composed of")
Rel_Realization_Up(BF_5, BS_2, "realizes")
@enduml
