@startuml Ex_02_Composition
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945990]]

title Example 2. Composition (Relationships)

Business_Function(BF_1, "Financial Processing\n(business function)")
Business_Function(BF_2, "Accounting\n(business function)")
Business_Function(BF_3, "Payment\n(business function)")
Business_Function(BF_4, "Billing\n(business function)")
Rel_Composition(BF_1, BF_2, "composed of")
Rel_Composition(BF_1, BF_3, "composed of")
Rel_Composition(BF_1, BF_4, "composed of")
@enduml
