@startuml Ex_01_Grouping
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap04.html#_Toc489945986]]

title Example 1. Grouping (Composite)

Business_Object(BO_1, "Object\n(business object)")
Business_Process(BP_1, "Process 2\n(business process)")
Business_Process(BP_2, "Process 1\n(business process)")
Business_Service(BS_1, "Service\n(business service)")
Grouping(CG_1, "Grouping\n(grouping)")
Rel_Access_w(BP_2, BO_1, "writes")
Rel_Aggregation_Down(CG_1, BO_1, "aggregates")
Rel_Aggregation_Down(CG_1, BP_2, "aggregates")
Rel_Aggregation_Down(CG_1, BP_1, "aggregates")
Rel_Triggering_Right(BP_2, BP_1, "triggers")
Rel_Realization_Up(CG_1, BS_1, "realizes")
@enduml
