@startuml Ex_13_AndJunction
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946004]]

title Example 13. (And) Junction (Relationships)

Business_Function(BF_12, "Sales\n(business function)")
Business_Function(BF_13, "Finance\n(business function)")
Business_Service(BS_5, "Invoicing\n(business service)")
Junction_And(JA_2, "(and)")
Rel_Realization(BF_12, JA_2, "realizes")
Rel_Realization(BF_13, JA_2, "realizes")
Rel_Realization(JA_2, BS_5, "realizes")
@enduml
