@startuml Ex_19_GoalOutcomePrincipleRequirementAndConstraint
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap06.html#_Toc489946022]]

title Example 19. Goal, Outcome, Principle, Requirement and Constraint (Motivation)

Motivation_Goal(MG_3, "Improve\nPortability Of\nService Offering\n(goal)")
Motivation_Outcome(MO_1, "Increased\nProfit\n(outcome)")
Motivation_Outcome(MO_2, "Increased\nRevenue\n(outcome)")
Motivation_Outcome(MO_3, "Reduced Cost Of\nCustomer acquisition\n(outcome)")
Motivation_Outcome(MO_4, "Increased Market\nShare\n(outcome)")
Motivation_Principle(MP_2, "Serve Customers\nWhenever They\nNeed Our Help\n(principle)")
Motivation_Principle(MP_3, "Serve Customers\nWherever They Are\n(principle)")
Motivation_Principle(MP_4, "Respond To Changing\nCustomer Needs,\nPreferences, And Expectations\nQuickly And Efficiently\n(principle)")
Motivation_Requirement(MR_1, "Services Shell Be\nAccessible Through\nMobile Browsers\n(requirement)")
Motivation_Requirement(MR_2, "Mobile Applications Shall\nRun On All Popular\nMobile Platforms\n(requirement)")
Rel_Influence(MO_2, MO_1, "+\n(influences)")
Rel_Influence(MO_3, MO_1, "+\n(influences)")
Rel_Influence(MO_4, MO_2, "+\n(influences)")
Rel_Realization(MO_1, MG_3, "realizes")
Rel_Realization(MP_2, MO_2, "realizes")
Rel_Realization(MP_3, MO_4, "realizes")
Rel_Realization(MP_4, MO_3, "realizes")
Rel_Realization(MR_1, MP_3, "realizes")
Rel_Realization(MR_2, MP_2, "realizes")
@enduml
