@startuml Ex_17_DerivedTriggeringRelationships
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946008]]

title Example 17. Derived Triggering Relationships (Relationships)

Business_Collaboration(BC_4, "Shipping Department\n(business collaboration)")
Business_Collaboration(BC_5, "Financial Department\n(business collaboration)")
Business_Collaboration(BC_6, "Sales Department\n(business collaboration)")
Business_Function(BF_20, "Shipping\n(business function)")
Business_Function(BF_21, "Billing & Payment\n(business function)")
Business_Function(BF_22, "Selling\n(business function)")
Rel_Association(BC_5, BC_4, "associated with")
Rel_Association(BC_6, BC_5, "associated with")
Rel_Association(BF_22, BF_20, "associated with")
Rel_Assignment_Right(BC_4, BF_20, "assigned to")
Rel_Assignment_Right(BC_5, BF_21, "assigned to")
Rel_Assignment_Right(BC_6, BF_22, "assigned to")
Rel_Triggering_Right(BF_21, BF_20, "triggers")
Rel_Triggering_Right(BF_22, BF_21, "triggers")
@enduml
