@startuml Ex_16_DerivedFlowRelationships
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946008]]

title Example 16. Derived Flow Relationships (Relationships)

Business_Collaboration(BC_2, "R&D Department\n(business collaboration)")
Business_Collaboration(BC_3, "Sales Department\n(business collaboration)")
Business_Function(BF_18, "Product Development\n(business function)")
Business_Function(BF_19, "Sales\n(business function)")
Business_Service(BS_10, "Development Service\n(business service)")
Business_Service(BS_9, "Sales Service\n(business service)")
Other_Location(OL_1, "London Office\n(location)")
Other_Location(OL_2, "Paris Office\n(location)")
Rel_Aggregation_Down(OL_1, BC_3, "aggregates")
Rel_Aggregation_Down(OL_2, BC_2, "aggregates")
Rel_Association_Right(BC_2, BF_19, "associated with")
Rel_Association(OL_2, OL_1, "associated with")
Rel_Assignment_Right(BC_2, BF_18, "assigned to")
Rel_Assignment_Right(BC_3, BF_19, "assigned to")
Rel_Flow_Right(BS_10, BS_9, "flows to")
Rel_Realization_Up(BF_18, BS_10, "realizes")
Rel_Realization_Up(BF_19, BS_9, "realizes")
@enduml
