@startuml Ex_11_Specialization
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946002]]

title Example 11. Specialization (Relationships)

Business_Process(BP_8, "Take Out\nInsurance\n(business process)")
Business_Process(BP_9, "Take Out\nTravel Insurance\n(business process)")
Business_Process(BP_10, "Take Out\nLuggage Insurance\n(business process)")
Rel_Specialization(BP_9, BP_8, "is specialization of")
Rel_Specialization(BP_10, BP_8, "is specialization of")
@enduml
