@startuml Ex_29_TechnologyBehaviorElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap10.html#_Toc489946098]]

title Example 30. Technology Behavior Elements (Technology)

Technology_Event(TE_1, "Database Update\n(technology event)")
Technology_Function(TF_2, "Handle Remote Updates\n(technology function)")
Technology_Function(TF_5, "Database Replication\n(technology function)")
Technology_Process(TP_1, "Remote Data Replication\n(technology process)")
Technology_Function(TF_1, "Handle Local Updates\n(technology function)")
Technology_Function(TF_4, "Administrate Replication\n(technology function)")
Technology_Function(TF_3, "Monitor Replication Status\n(technology function)")
Technology_Service(TS_1, "Replicate Database Updates\n(technology service)")
Rel_Serving(TS_1, TP_1, "serves")
Rel_Composition(TF_5, TF_4, "composed of")
Rel_Flow(TF_4, TF_3, "flows to")
Rel_Triggering(TE_1, TP_1, "triggers")
Rel_Composition(TF_5, TF_1, "composed of")
Rel_Composition(TF_5, TF_3, "composed of")
Rel_Flow(TF_4, TF_1, "flows to")
Rel_Flow(TF_4, TF_2, "flows to")
Rel_Realization(TF_5, TS_1, "realizes")
Rel_Composition(TF_5, TF_2, "composed of")
@enduml
