@startuml Ex_23_BusinessBehaviorElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap08.html#_Toc489946053]]

title Example 23. Business Behavior Elemenst (Business)

Business_Collaboration(BC_8, "High-Risk\nClaims\nAdjudcation\n(business collaboration)")
Business_Event(BE_6, "Claim Filed\n(business event)")
Business_Function(BF_23, "Claims Administration\n(business function)")
Business_Interaction(BI_1, "Adjudcate\nHigh-Risk Claim\n(business interaction)")
Business_Process(BP_15, "Notify\nCustomer\n(business process)")
Business_Process(BP_16, "Play\nClaim\n(business process)")
Business_Process(BP_17, "Close\nClaim\n(business process)")
Business_Process(BP_18, "Adjudcate\nStandard Claim\n(business process)")
Business_Process(BP_19, "Assign\nClaim\n(business process)")
Business_Process(BP_20, "Accept\nClaim\n(business process)")
Business_Role(BR_6, "Customer\nService\nRepresentative\n(business role)")
Business_Role(BR_7, "Specialist\n(business role)")
Business_Service(BS_11, "Claims Processing\n(business service)")
Junction_And(JA_3, "(and)")
Junction_And(JA_4, "(and)")
Junction_Or(JO_2, "(or)")
Junction_Or(JO_3, "(or)")
Rel_Aggregation_Down(BC_8, BR_6, "aggregates")
Rel_Aggregation_Down(BC_8, BR_7, "aggregates")
Rel_Assignment_Right(BR_6, BP_20, "assigned to")
Rel_Assignment_Right(BR_7, BP_18, "assigned to")
Rel_Assignment_Right(BC_8, BP_19, "assigned to")
Rel_Assignment_Right(BC_8, BI_1, "assigned to")
Rel_Composition_Down(BF_23, BP_20, "composed of")
Rel_Composition_Down(BF_23, BP_19, "composed of")
Rel_Composition_Down(BF_23, BP_18, "composed of")
Rel_Composition_Down(BF_23, BI_1, "composed of")
Rel_Composition_Down(BF_23, BP_15, "composed of")
Rel_Composition_Down(BF_23, BP_16, "composed of")
Rel_Composition_Down(BF_23, BP_17, "composed of")
Rel_Triggering_Right(BP_15, JA_3, "triggers")
Rel_Triggering_Right(BP_16, JA_3, "triggers")
Rel_Triggering_Right(JA_3, BP_17, "triggers")
Rel_Triggering_Right(BP_18, JO_2, "triggers")
Rel_Triggering_Right(BI_1, JO_2, "triggers")
Rel_Triggering_Right(JO_2, JA_4, "triggers")
Rel_Triggering_Right(JA_4, BP_15, "triggers")
Rel_Triggering_Right(JA_4, BP_16, "triggers")
Rel_Triggering_Right(BP_19, JO_3, "triggers")
Rel_Triggering_Right(JO_3, BP_18, "triggers")
Rel_Triggering_Right(JO_3, BI_1, "triggers")
Rel_Triggering_Right(BP_20, BP_19, "triggers")
Rel_Triggering_Right(BE_6, BP_20, "triggers")
Rel_Realization_Up(BF_23, BS_11, "realizes")
@enduml
