@startuml Ex_29_TechnologyActiveStructureElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap10.html#_Toc489946091]]

title Example 29. Technology Active Structure Elements (Technology)

Technology_Device(TD_2, "Blade System 1\n(device)")
Technology_Interface(TIf_3, "Management Interface\n(technology interface)")
Technology_Node(TN_2, "Purchase Virtual Host\n(node)")
Junction_And(JA_5, "(and)")
Technology_SystemSoftware(TSS_1, "Open Source Operating System\n(system software)")
Technology_SystemSoftware(TSS_2, "Proprietary Operating System\n(system software)")
Technology_CommunicationNetwork(TCN_2, "Wide Area Network\n(communication network)")
Technology_CommunicationNetwork(TCN_1, "Data Center Network\n(communication network)")
Technology_Interface(TIf_1, "Management Interface\n(technology interface)")
Technology_Path(TPa_1, "Data Replication Path\n(path)")
Technology_Node(TN_1, "Quotation Virtual Host\n(node)")
Technology_SystemSoftware(TSS_3, "Hypervisor\n(system software)")
Technology_Device(TD_1, "Blade System 2\n(device)")
Technology_Collaboration(TC_1, "E-Commerce Hosting\n(technology collaboration)")
Technology_Node(TN_3, "Data Center Switch\n(node)")
Rel_Composition(TD_2, TIf_1, "composed of")
Rel_Aggregation(TC_1, TSS_3, "aggregates")
Rel_Aggregation(TC_1, TN_1, "aggregates")
Rel_Assignment(TSS_3, TSS_2, "assigned to")
Rel_Aggregation(TN_1, TSS_1, "aggregates")
Rel_Realization(JA_5, TPa_1, "realizes")
Rel_Association(TCN_1, TD_1, "associated with")
Rel_Assignment(TD_2, TSS_3, "assigned to")
Rel_Association(TCN_1, TD_2, "associated with")
Rel_Composition(TN_3, TIf_3, "composed of")
Rel_Realization(TCN_2, JA_5, "realizes")
Rel_Composition(TD_1, TIf_1, "composed of")
Rel_Association(TCN_2, TN_3, "associated with")
Rel_Assignment(TSS_3, TSS_1, "assigned to")
Rel_Aggregation(TC_1, TN_2, "aggregates")
Rel_Association(TCN_1, TN_3, "associated with")
Rel_Aggregation(TN_2, TSS_2, "aggregates")
Rel_Realization(TCN_1, JA_5, "realizes")
@enduml
