@startuml Ex_21_StrategyElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap07.html#_Toc489946036]]

title Example 21. Strategy Elements

Motivation_Goal(MG_4, "Decrease Costs\n(goal)")
Motivation_Goal(MG_5, "Increase Revenue\n(goal)")
Motivation_Goal(MG_6, "Increase Profit\n(goal)")
Motivation_Outcome(MO_5, "Decreased\nCosts\n(outcome)")
Motivation_Outcome(MO_6, "Loss of\nCustomers\n(outcome)")
Other_Location(OL_3, "Headquarters\n(location)")
Strategy_CourseOfAction(SCOA_1, "Centralize IT\nSystems\n(course of action)")
Strategy_CourseOfAction(SCOA_2, "Standartize\nProducts\n(course of action)")
Strategy_CourseOfAction(SCOA_3, "Operational\nExcellence\n(course of action)")
Strategy_Capability(SC_1, "IT\nManagement &\nOperations\n(capability)")
Strategy_Capability(SC_2, "Product\nManagement\n(capability)")
Strategy_Resource(SR_1, "Human\nResources\n(resource)")
Strategy_Resource(SR_2, "IT\nResources\n(resource)")
Rel_Aggregation(SCOA_3, SCOA_1, "aggregates")
Rel_Aggregation(SCOA_3, SCOA_2, "aggregates")
Rel_Aggregation(OL_3, SR_1, "aggregates")
Rel_Aggregation(OL_3, SR_2, "aggregates")
Rel_Aggregation(MG_6, MG_4, "aggregates")
Rel_Aggregation(MG_6, MG_5, "aggregates")
Rel_Association(SCOA_3, MG_4, "associated with")
Rel_Assignment(SR_1, SC_1, "assigned to")
Rel_Assignment(SR_2, SC_1, "assigned to")
Rel_Influence(MO_5, MG_4, "+\n(influences)")
Rel_Influence(MO_6, MG_5, "-\n(influences)")
Rel_Influence(SCOA_1, MO_5, "+\n(influences)")
Rel_Influence(SCOA_2, MO_5, "+\n(influences)")
Rel_Influence(SCOA_2, MO_6, "+\n(influences)")
Rel_Realization(SC_1, SCOA_1, "realizes")
Rel_Realization(SC_2, SCOA_2, "realizes")
@enduml
