@startuml Ex_34_ImplementationAndMigrationElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap13.html#_Toc489946127]]

title Example 34. Implementation and Migration Elements (Implementation and Migration)

Implementation_Deliverable(ID_3, "Roadmap\n(deliverable)")
Implementation_Gap(IG_3, "Consumer Internet And Mobile Access To Insurance Services\n(gap)")
Implementation_Plateau(IP_4, "Next Generation Services In Place\n(plateau)")
Junction_And(JA_7, "(and)")
Implementation_Deliverable(ID_2, "Architecture\n(deliverable)")
Implementation_WorkPackage(IWP_3, "Application Services Layer Development\n(work package)")
Implementation_WorkPackage(IWP_2, "Architecture And Planning\n(work package)")
Implementation_Plateau(IP_3, "Application Services Layer In Place\n(plateau)")
Implementation_WorkPackage(IWP_4, "Business Services Development\n(work package)")
Implementation_Plateau(IP_1, "Baseline\n(plateau)")
Implementation_Gap(IG_1, "Knowledge Of How To Address Customer Needs\n(gap)")
Implementation_Event(IE_2, "Program Approved\n(implementation event)")
Implementation_Plateau(IP_2, "Strategic Plan Complete\n(plateau)")
Implementation_Gap(IG_2, "Programmatic Internet Access To Core Systems And Data\n(gap)")
Implementation_Deliverable(ID_6, "Program Brief\n(deliverable)")
Implementation_WorkPackage(IWP_1, "Next Generation Services Program\n(work package)")
Implementation_Deliverable(ID_4, "Services Platform\n(deliverable)")
Implementation_Deliverable(ID_5, "Business Services\n(deliverable)")
Implementation_Deliverable(ID_1, "Business Plan\n(deliverable)")
Implementation_Event(IE_1, "Program Complete\n(implementation event)")
Rel_Access(IWP_2, ID_6, "accesses")
Rel_Realization(IWP_2, ID_1, "realizes")
Rel_Composition(IWP_1, IWP_3, "composed of")
Rel_Realization(ID_3, JA_7, "realizes")
Rel_Association(IG_2, IP_2, "associated with")
Rel_Triggering(IWP_4, IE_1, "triggers")
Rel_Association(IG_1, IP_2, "associated with")
Rel_Realization(ID_2, JA_7, "realizes")
Rel_Triggering(IP_3, IP_4, "triggers")
Rel_Access(IE_2, ID_6, "accesses")
Rel_Association(IG_3, IP_3, "associated with")
Rel_Realization(ID_4, IP_3, "realizes")
Rel_Composition(IWP_1, IWP_4, "composed of")
Rel_Access(IWP_3, ID_3, "accesses")
Rel_Triggering(IWP_2, IWP_3, "triggers")
Rel_Association(IG_1, IP_1, "associated with")
Rel_Realization(JA_7, IP_2, "realizes")
Rel_Triggering(IE_2, IWP_2, "triggers")
Rel_Access(IWP_4, ID_4, "accesses")
Rel_Realization(IWP_2, ID_3, "realizes")
Rel_Realization(ID_1, JA_7, "realizes")
Rel_Realization(ID_5, IP_4, "realizes")
Rel_Association(IG_3, IP_4, "associated with")
Rel_Realization(IWP_3, ID_4, "realizes")
Rel_Triggering(IP_1, IP_2, "triggers")
Rel_Association(IG_2, IP_3, "associated with")
Rel_Realization(IWP_4, ID_5, "realizes")
Rel_Realization(IWP_2, ID_2, "realizes")
Rel_Triggering(IP_2, IP_3, "triggers")
Rel_Triggering(IWP_3, IWP_4, "triggers")
Rel_Composition(IWP_1, IWP_2, "composed of")
@enduml
