@startuml Ex_33_CrossLayerRelationships
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap12.html#_Toc489946118]]

title Example 33. Cross-Layer Relationships (Cross-Layer)

Application_Component(ACmp_4, "CRM System\n(application component)")
Application_Component(ACmp_5, "Financial application\n(application component)")
Application_DataObject(ADO_11, "Customer Data\n(data object)")
Application_Service(AS_5, "Customer Data Management\n(application service)")
Application_Service(AS_6, "Payment Processing\n(application service)")
Business_Actor(BA_5, "Customer\n(business actor)")
Business_Actor(BA_6, "ArchiSurance\n(business actor)")
Business_Object(BO_11, "Customer Information\n(business object)")
Business_Process(BP_21, "Process Claims\n(business process)")
Business_Process(BP_22, "Register\n(business process)")
Business_Process(BP_23, "Accept\n(business process)")
Business_Process(BP_24, "Adjudicate\n(business process)")
Business_Process(BP_25, "Pay\n(business process)")
Business_Role(BR_8, "Insurant\n(business role)")
Business_Role(BR_9, "Insurer\n(business role)")
Business_Service(BS_18, "Claims Registration\n(business service)")
Business_Service(BS_19, "Claims Acceptance\n(business service)")
Business_Service(BS_20, "Claims Payment\n(business service)")
Technology_Artifact(TA_7, "Customer Database Tables\n(artifact)")
Technology_Artifact(TA_8, "Database Access Java Archive\n(artifact)")
Technology_Artifact(TA_9, "Financial Application Web Archive\n(artifact)")
Technology_Device(TD_3, "Blade System\n(device)")
Technology_SystemSoftware(TSS_4, "Database Management System\n(system software)")
Technology_SystemSoftware(TSS_5, "Application Server\n(system software)")
Technology_Service(TS_2, "Database Management\n(technology service)")
Technology_Service(TS_3, "Application Hosting\n(technology service)")
Rel_Access_w(BP_22, BO_11, "writes")
Rel_Access_w(ACmp_4, ADO_11, "writes")
Rel_Access_w(TS_2, TA_7, "writes")
Rel_Assignment(BA_5, BR_8, "assigned to")
Rel_Assignment(BR_9, BP_21, "assigned to")
Rel_Assignment(BA_6, BR_9, "assigned to")
Rel_Assignment(TSS_4, TA_8, "assigned to")
Rel_Assignment(TSS_5, TA_9, "assigned to")
Rel_Assignment(TD_3, TSS_4, "assigned to")
Rel_Assignment(TD_3, TSS_5, "assigned to")
Rel_Composition(BP_21, BP_22, "composed of")
Rel_Composition(BP_21, BP_23, "composed of")
Rel_Composition(BP_21, BP_24, "composed of")
Rel_Composition(BP_21, BP_25, "composed of")
Rel_Serving(BS_18, BR_8, "serves")
Rel_Serving(BS_19, BR_8, "serves")
Rel_Serving(BS_20, BR_8, "serves")
Rel_Serving(AS_5, BP_22, "serves")
Rel_Serving(AS_6, BP_25, "serves")
Rel_Serving(TS_2, ACmp_4, "serves")
Rel_Serving(TS_3, ACmp_4, "serves")
Rel_Serving(TS_3, ACmp_5, "serves")
Rel_Triggering(BP_24, BP_25, "triggers")
Rel_Triggering(BP_23, BP_24, "triggers")
Rel_Triggering(BP_22, BP_23, "triggers")
Rel_Realization(BP_22, BS_18, "realizes")
Rel_Realization(BP_23, BS_19, "realizes")
Rel_Realization(BP_25, BS_20, "realizes")
Rel_Realization(ADO_11, BO_11, "realizes")
Rel_Realization(TA_7, ADO_11, "realizes")
Rel_Realization(TA_8, ACmp_4, "realizes")
Rel_Realization(TSS_4, TS_2, "realizes")
Rel_Realization(TA_9, ACmp_5, "realizes")
Rel_Realization(TSS_5, TS_3, "realizes")
@enduml
