@startuml Ex_31_TechnologyPassiveStructureElement
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap10.html#_Toc489946102]]

title Example 31. Technology Passive Structure Element: Artifact (Technology)

Technology_Artifact(TA_1, "Travel Insurance Database\n(artifact)")
Technology_Artifact(TA_2, "Database Access Java Archive\n(artifact)")
Technology_Artifact(TA_3, "Business Logic Java Archive\n(artifact)")
Technology_Artifact(TA_4, "Web Archive\n(artifact)")
Technology_Artifact(TA_5, "Purchase Application Web Archive\n(artifact)")
Technology_Artifact(TA_6, "Quotation Application Web Archive\n(artifact)")
Rel_Association(TA_4, TA_1, "associated with")
Rel_Composition_Down(TA_4, TA_2, "composed of")
Rel_Composition_Down(TA_4, TA_3, "composed of")
Rel_Specialization_Up(TA_5, TA_4, "is specialization of")
Rel_Specialization_Up(TA_6, TA_4, "is specialization of")
@enduml
