@startuml Ex_02_Composition
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945990

title Example 2. Composition (Relationships)

Business_Function(BF_1, "Financial Processing\n(business function)")
Business_Function(BF_2, "Accounting\n(business function)")
Business_Function(BF_4, "Billing\n(business function)")
Business_Function(BF_3, "Payment\n(business function)")
Rel_Composition(BF_1, BF_2, "composed of")
Rel_Composition(BF_1, BF_3, "composed of")
Rel_Composition(BF_1, BF_4, "composed of")
@enduml
@startuml Ex_03_Aggregation
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945991

title Example 3. Aggregation (Relationships)

Business_Object(BO_3, "Insurance Policy\n(business object)")
Business_Object(BO_2, "Customer File\n(business object)")
Business_Object(BO_4, "Insurance Claim\n(business object)")
Rel_Aggregation(BO_2, BO_3, "aggregates")
Rel_Aggregation(BO_2, BO_4, "aggregates")
@enduml
@startuml Ex_04_Assignment
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945992

title Example 4. Assignment (Relationships)

Business_Collaboration(BC_1, "Finance\n(business collaboration)")
Business_Interface(BIf_1, "Payment Interface\n(business interface)")
Business_Function(BF_5, "Transaction Processing\n(business function)")
Business_Service(BS_2, "Payment Service\n(business service)")
Rel_Realization(BF_5, BS_2, "realizes")
Rel_Assignment(BIf_1, BS_2, "assigned to")
Rel_Composition(BC_1, BIf_1, "composed of")
Rel_Assignment(BC_1, BF_5, "assigned to")
@enduml
@startuml Ex_05_Realization
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945993

title Example 5. Realization (Relationships)

Business_Service(BS_3, "Billing Service\n(business service)")
Business_Representation(BRep_1, "Paper Invoice\n(representation)")
Business_Object(BO_5, "Billing Data\n(business object)")
Business_Function(BF_6, "Transaction Processing\n(business function)")
Rel_Realization(BF_6, BS_3, "realizes")
Rel_Access(BS_3, BO_5, "accesses")
Rel_Realization(BRep_1, BO_5, "realizes")
@enduml
@startuml Ex_06_Serving
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945993

title Example 6. Serving (Relationships)

Business_Process(BP_3, "Pay Invoices\n(business process)")
Business_Interface(BIf_2, "Payment Interface\n(business interface)")
Business_Service(BS_4, "Payment Service\n(business service)")
Business_Role(BR_1, "Customer\n(business role)")
Rel_Serving(BS_4, BP_3, "serves")
Rel_Assignment(BIf_2, BS_4, "assigned to")
Rel_Serving(BIf_2, BR_1, "serves")
Rel_Assignment(BR_1, BP_3, "assigned to")
@enduml
@startuml Ex_07_Access
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945996

title Example 7. Access (Relationships)

Business_Process(BP_4, "Send Invoice\n(business process)")
Business_Event(BE_2, "Invoice Request\n(business event)")
Business_Object(BO_6, "Invoice\n(business object)")
Business_Event(BE_1, "Invoice Sent\n(business event)")
Business_Process(BP_5, "Create Invoice\n(business process)")
Rel_Access(BP_5, BO_6, "accesses")
Rel_Triggering(BP_4, BE_1, "triggers")
Rel_Access(BP_4, BO_6, "accesses")
Rel_Triggering(BE_2, BP_5, "triggers")
Rel_Triggering(BP_5, BP_4, "triggers")
@enduml
@startuml Ex_08_Influence
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945993

title Example 8. Influence (Relationships)

Motivation_Goal(MG_2, "Decrease Costs\n(goal)")
Motivation_Goal(MG_1, "Reduce Workload\nOf Employees\n(goal)")
Motivation_Principle(MP_1, "Assign Personal\nAssistant\n(principle)")
Rel_Influence(MP_1, MG_2, "influences (--)")
Rel_Influence(MP_1, MG_1, "influences (++)")
@enduml
@startuml Ex_09_Triggering
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489945999

title Example 9. Triggering (Relationships)

Business_Process(BP_7, "Create Invoice\n(business process)")
Business_Process(BP_6, "Send Invoice\n(business process)")
Business_Event(BE_4, "Invoice Requested\n(business event)")
Business_Event(BE_3, "Invoice Sent\n(business event)")
Rel_Triggering(BE_4, BP_7, "triggers")
Rel_Triggering(BP_6, BE_3, "triggers")
Rel_Triggering(BP_7, BP_6, "triggers")
@enduml
@startuml Ex_10_Flow
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946000

title Example 10. Flow (Relationships)

Business_Function(BF_7, "Claim Settlement\n(business function)")
Business_Function(BF_8, "Claim Assessment\n(business function)")
Business_Function(BF_9, "Scheduling\n(business function)")
Rel_Flow(BF_8, BF_7, "flows to")
Rel_Flow(BF_9, BF_8, "flows to")
@enduml
@startuml Ex_11_Specialization
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946002

title Example 11. Specialization (Relationships)

Business_Process(BP_8, "Take Out\nInsurance\n(business process)")
Business_Process(BP_9, "Take Out\nTravel Insurance\n(business process)")
Business_Process(BP_10, "Take Out\nLuggage Insurance\n(business process)")
Rel_Specialization(BP_9, BP_8, "is specialization of")
Rel_Specialization(BP_10, BP_8, "is specialization of")
@enduml
@startuml Ex_12_Association
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946003

title Example 12. Association (Relationships)

Business_Function(BF_10, "Policy Management\n(business function)")
Business_Function(BF_11, "Policy Creation\n(business function)")
Rel_Flow(BF_11, BF_10, "flows to")
@enduml
@startuml Ex_13_AndJunction
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946004

title Example 13. (And) Junction (Relationships)

Business_Function(BF_13, "Finance\n(business function)")
Junction_And(JA_1, "(and)")
Business_Service(BS_5, "Invoicing\n(business service)")
Business_Function(BF_12, "Sales\n(business function)")
Rel_Realization(JA_1, BS_5, "realizes")
Rel_Realization(BF_13, JA_1, "realizes")
Rel_Realization(BF_12, JA_1, "realizes")
@enduml
@startuml Ex_14_OrJunction
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946004

title Example 14. Or Junction (Relationships)

Business_Process(BP_11, "Accept Request\n(business process)")
Business_Process(BP_12, "Reject Request\n(business process)")
Junction_Or(JO_1, "(or)")
Business_Event(BE_5, "Request Received\n(business event)")
Business_Process(BP_13, "Assess Request\n(business process)")
Rel_Triggering(BE_5, BP_13, "triggers")
Rel_Triggering(BP_13, JO_1, "triggers")
Rel_Triggering(JO_1, BP_11, "triggers")
Rel_Triggering(JO_1, BP_12, "triggers")
@enduml
@startuml Ex_15_DerivedStructuralAndDependencyRelationship
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946007

title Example 15. Derived Structural and Dependency Relationship (Relationships)

Business_Function(BF_16, "Payment\n(business function)")
Business_Process(BP_14, "Invoicing and Collections\n(business process)")
Business_Function(BF_15, "Billing\n(business function)")
Application_Service(AS_1, "Financial Application\n(application service)")
Business_Function(BF_14, "Accounting\n(business function)")
Business_Service(BS_8, "Payment Service\n(business service)")
Business_Service(BS_7, "Billing Service\n(business service)")
Business_Service(BS_6, "Accounting Service\n(business service)")
Business_Function(BF_17, "Financial Processing\n(business function)")
Rel_Serving(AS_1, BF_17, "serves")
Rel_Composition(BF_17, BF_15, "composed of")
Rel_Serving(BS_6, BP_14, "serves")
Rel_Realization(BF_14, BS_6, "realizes")
Rel_Serving(AS_1, BP_14, "serves")
Rel_Serving(BS_8, BP_14, "serves")
Rel_Realization(BF_16, BS_8, "realizes")
Rel_Realization(BF_15, BS_7, "realizes")
Rel_Composition(BF_17, BF_14, "composed of")
Rel_Serving(BS_7, BP_14, "serves")
Rel_Composition(BF_17, BF_16, "composed of")
@enduml
@startuml Ex_16_DerivedFlowRelationships
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946008

title Example 16. Derived Flow Relationships (Relationships)

Business_Service(BS_10, "Development Service\n(business service)")
Business_Function(BF_19, "Sales\n(business function)")
Business_Collaboration(BC_3, "Sales Department\n(business collaboration)")
Business_Function(BF_18, "Product Development\n(business function)")
Business_Collaboration(BC_2, "R&D Department\n(business collaboration)")
Business_Service(BS_9, "Sales Service\n(business service)")
Rel_Assignment(BC_3, BF_19, "assigned to")
Rel_Realization(BF_18, BS_10, "realizes")
Rel_Realization(BF_19, BS_9, "realizes")
Rel_Assignment(BC_2, BF_18, "assigned to")
Rel_Flow(BS_10, BS_9, "flows to")
@enduml
@startuml Ex_17_DerivedTriggeringRelationships
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946008

title Example 17. Derived Triggering Relationships (Relationships)

Business_Function(BF_22, "Selling\n(business function)")
Business_Function(BF_21, "Billing & Payment\n(business function)")
Business_Collaboration(BC_4, "Sales Department\n(business collaboration)")
Business_Function(BF_20, "Shipping\n(business function)")
Business_Collaboration(BC_5, "Financial Department\n(business collaboration)")
Business_Collaboration(BC_6, "Shipping Department\n(business collaboration)")
Rel_Triggering(BF_22, BF_21, "triggers")
Rel_Triggering(BF_22, BF_20, "triggers")
Rel_Assignment(BC_4, BF_22, "assigned to")
Rel_Assignment(BC_5, BF_21, "assigned to")
Rel_Assignment(BC_6, BF_20, "assigned to")
Rel_Triggering(BF_21, BF_20, "triggers")
@enduml
@startuml Ex_18_StakeholderDriverAndAssessment
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap06.html#_Toc489946015

title Example 18. Stakeholder, Driver and Assessment (Motivation)

Motivation_Stakeholder(MS_1, "Chief Marketing\nOfficer (CMO)\n(stakeholder)")
Motivation_Assessment(MA_6, "Discounts Provided\nTo Remain\nCompetitive\n(assessment)")
Motivation_Driver(MD_4, "Costs\n(driver)")
Motivation_Assessment(MA_1, "Market Share is\nDeclining\n(assessment)")
Motivation_Stakeholder(MS_2, "Chief Executive\nOfficer (CEO)\n(stakeholder)")
Motivation_Driver(MD_3, "Profitability\n(driver)")
Motivation_Assessment(MA_4, "Cost Of\nAcquiring New\nCustomers Is\nIncreasing\n(assessment)")
Motivation_Stakeholder(MS_3, "Chief Financial\nOfficer (CFO)\n(stakeholder)")
Motivation_Assessment(MA_2, "Revenue is\nDeclining\n(assessment)")
Motivation_Driver(MD_1, "Market Share\n(driver)")
Motivation_Assessment(MA_5, "Competitors Are Including\nAdvanced Features In\nTheir Service Models\n(assessment)")
Motivation_Assessment(MA_3, "Profitability is\nDeclining\n(assessment)")
Motivation_Driver(MD_2, "Revenue\n(driver)")
Rel_Influence(MA_1, MA_2, "influences (+)")
Rel_Influence(MA_6, MA_2, "influences (+)")
Rel_Association(MS_2, MD_3, "associated with")
Rel_Influence(MA_5, MA_6, "influences (+)")
Rel_Influence(MA_5, MA_1, "influences (+)")
Rel_Association(MS_3, MD_3, "associated with")
Rel_Composition(MD_3, MD_4, "composed of")
Rel_Influence(MA_6, MA_1, "influences (-)")
Rel_Composition(MD_3, MD_2, "composed of")
Rel_Influence(MA_2, MA_3, "influences (+)")
Rel_Influence(MA_4, MA_3, "influences (+)")
Rel_Association(MD_2, MA_2, "associated with")
Rel_Association(MD_4, MA_4, "associated with")
Rel_Association(MD_1, MA_1, "associated with")
Rel_Association(MD_3, MA_3, "associated with")
Rel_Association(MS_2, MD_1, "associated with")
Rel_Association(MS_1, MD_1, "associated with")
@enduml
@startuml Ex_19_GoalOutcomePrincipleRequirementAndConstraint
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap06.html#_Toc489946022

title Example 19. Goal, Outcome, Principle, Requirement and Constraint (Motivation)

Motivation_Requirement(MR_1, "Services Shell Be\nAccessible Through\nMobile Browsers\n(requirement)")
Motivation_Outcome(MO_2, "Increased\nRevenue\n(outcome)")
Motivation_Principle(MP_4, "Respond To Changing\nCustomer Needs,\nPreferences, And Expectations\nQuickly And Efficiently\n(principle)")
Motivation_Principle(MP_2, "Serve Customers\nWhenever They\nNeed Our Help\n(principle)")
Motivation_Goal(MG_3, "Improve\nPortability Of\nService Offering\n(goal)")
Motivation_Requirement(MR_2, "Mobile Applications Shall\nRun On All Popular\nMobile Platforms\n(requirement)")
Motivation_Outcome(MO_4, "Increased Market\nShare\n(outcome)")
Motivation_Outcome(MO_1, "Increased\nProfit\n(outcome)")
Motivation_Principle(MP_3, "Serve Customers\nWherever They Are\n(principle)")
Motivation_Outcome(MO_3, "Reduced Cost Of\nCustomer acquisition\n(outcome)")
Rel_Realization(MP_2, MO_2, "realizes")
Rel_Realization(MP_4, MO_3, "realizes")
Rel_Influence(MO_3, MO_1, "influences (+)")
Rel_Realization(MR_1, MP_3, "realizes")
Rel_Realization(MR_2, MP_2, "realizes")
Rel_Influence(MO_4, MO_2, "influences (+)")
Rel_Realization(MP_3, MO_4, "realizes")
Rel_Influence(MO_2, MO_1, "influences (+)")
Rel_Realization(MO_1, MG_3, "realizes")
@enduml
@startuml Ex_20_MeaningAndValue
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap06.html#_Toc489946026

title Example 20. Meaning and Value (Motivation)

Motivation_Value(MV_1, "Cost Efficiency\n(value)")
Motivation_Value(MV_4, "Certainty\n(value)")
Application_DataObject(ADO_4, "Payment Complete\nMessage\n(data object)")
Application_DataObject(ADO_1, "Message\n(data object)")
Motivation_Stakeholder(MS_5, "Customer\n(stakeholder)")
Motivation_Meaning(MM_3, "Claim Has\nBeen Paid\n(meaning)")
Application_Service(AS_2, "Push Notification\n(application service)")
Application_DataObject(ADO_2, "Confirmation Of\nReceipt Message\n(data object)")
Motivation_Value(MV_3, "Peace of Mind\n(value)")
Motivation_Stakeholder(MS_4, "Insurer\n(stakeholder)")
Motivation_Meaning(MM_1, "Claim Has\nBeen\nReceived\n(meaning)")
Motivation_Meaning(MM_2, "Claim Review\nComplete\n(meaning)")
Motivation_Value(MV_2, "Being Informed\n(value)")
Application_DataObject(ADO_3, "Review Complete\nMessage\n(data object)")
Rel_Association(AS_2, MV_1, "associated with")
Rel_Association(ADO_4, MM_3, "associated with")
Rel_Specialization(ADO_4, ADO_1, "is specialization of")
Rel_Association(ADO_3, MM_2, "associated with")
Rel_Association(MS_4, MV_1, "associated with")
Rel_Association(AS_2, MV_2, "associated with")
Rel_Specialization(ADO_2, ADO_1, "is specialization of")
Rel_Composition(MV_3, MV_4, "composed of")
Rel_Access(AS_2, ADO_1, "accesses")
Rel_Association(MS_5, MV_3, "associated with")
Rel_Association(AS_2, MV_3, "associated with")
Rel_Association(MS_5, MV_2, "associated with")
Rel_Specialization(ADO_3, ADO_1, "is specialization of")
Rel_Association(ADO_2, MM_1, "associated with")
@enduml
@startuml Ex_22_BusinessActiveStructureElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap08.html#_Toc489946046

title Example 22. Business Active Structure Elements

Business_Interface(BIf_3, "Phone\n(business interface)")
Business_Role(BR_5, "Customer\nService\nRepresentative\n(business role)")
Business_Actor(BA_4, "ArchiSurance Contact Center\n(business actor)")
Business_Role(BR_2, "Specialist\n(business role)")
Business_Interface(BIf_5, "Web\nChat\n(business interface)")
Business_Actor(BA_1, "Greg\n(business actor)")
Business_Collaboration(BC_7, "High-Risk\nClaims\nAdjudication\n(business collaboration)")
Business_Actor(BA_2, "Joan\n(business actor)")
Business_Interface(BIf_4, "E-Mail\n(business interface)")
Business_Role(BR_3, "Travel\nInsurance\nClaim Analyst\n(business role)")
Business_Role(BR_4, "Home Insurance\nProduct\nSpecialist\n(business role)")
Business_Actor(BA_3, "Larry\n(business actor)")
Rel_Composition(BA_4, BIf_5, "composed of")
Rel_Composition(BA_4, BIf_4, "composed of")
Rel_Assignment(BA_3, BR_5, "assigned to")
Rel_Specialization(BR_4, BR_2, "is specialization of")
Rel_Assignment(BA_2, BR_4, "assigned to")
Rel_Aggregation(BC_7, BR_5, "aggregates")
Rel_Aggregation(BC_7, BR_2, "aggregates")
Rel_Composition(BA_4, BIf_3, "composed of")
Rel_Composition(BA_4, BA_2, "composed of")
Rel_Assignment(BA_1, BR_3, "assigned to")
Rel_Composition(BA_4, BA_3, "composed of")
Rel_Composition(BA_4, BA_1, "composed of")
Rel_Specialization(BR_3, BR_2, "is specialization of")
@enduml
@startuml Ex_23_BusinessBehaviorElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap08.html#_Toc489946053

title Example 23. Business Behavior Elemenst (Business)

Junction_And(JA_2, "(and)")
Business_Collaboration(BC_8, "High-Risk\nClaims\nAdjudcation\n(business collaboration)")
Business_Service(BS_11, "Claims Processing\n(business service)")
Business_Process(BP_17, "Close\nClaim\n(business process)")
Junction_Or(JO_3, "(or)")
Business_Process(BP_20, "Accept\nClaim\n(business process)")
Business_Event(BE_6, "Claim Filed\n(business event)")
Business_Role(BR_7, "Specialist\n(business role)")
Junction_Or(JO_2, "(or)")
Business_Function(BF_23, "Claims Administration\n(business function)")
Business_Process(BP_19, "Assign\nClaim\n(business process)")
Business_Process(BP_15, "Notify\nCustomer\n(business process)")
Business_Process(BP_16, "Play\nClaim\n(business process)")
Business_Process(BP_18, "Adjudcate\nStandard Claim\n(business process)")
Junction_And(JA_3, "(and)")
Business_Interaction(BI_1, "Adjudcate\nHigh-Risk Claim\n(business interaction)")
Business_Role(BR_6, "Customer\nService\nRepresentative\n(business role)")
Rel_Assignment(BR_7, BP_18, "assigned to")
Rel_Triggering(BP_19, JO_3, "triggers")
Rel_Composition(BF_23, BP_16, "composed of")
Rel_Aggregation(BC_8, BR_6, "aggregates")
Rel_Triggering(JO_2, JA_3, "triggers")
Rel_Triggering(BP_18, JO_2, "triggers")
Rel_Composition(BF_23, BP_17, "composed of")
Rel_Triggering(BI_1, JO_2, "triggers")
Rel_Composition(BF_23, BP_18, "composed of")
Rel_Assignment(BC_8, BP_19, "assigned to")
Rel_Triggering(BP_16, JA_2, "triggers")
Rel_Aggregation(BC_8, BR_7, "aggregates")
Rel_Triggering(JA_3, BP_16, "triggers")
Rel_Composition(BF_23, BP_19, "composed of")
Rel_Composition(BF_23, BP_20, "composed of")
Rel_Triggering(BE_6, BP_20, "triggers")
Rel_Composition(BF_23, BP_15, "composed of")
Rel_Assignment(BC_8, BI_1, "assigned to")
Rel_Assignment(BR_6, BP_20, "assigned to")
Rel_Triggering(JA_2, BP_17, "triggers")
Rel_Triggering(JO_3, BI_1, "triggers")
Rel_Realization(BF_23, BS_11, "realizes")
Rel_Triggering(JO_3, BP_18, "triggers")
Rel_Triggering(JA_3, BP_15, "triggers")
Rel_Triggering(BP_15, JA_2, "triggers")
Rel_Composition(BF_23, BI_1, "composed of")
Rel_Triggering(BP_20, BP_19, "triggers")
@enduml
@startuml Ex_24_BusinessPassiveStructureElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap08.html#_Toc489946058

title Example 24. Business Passive Structure Elements (Business)

Business_Contract(BCn_1, "Insurance Policy\n(contract)")
Business_Representation(BRep_3, "Claim File\nSummary\n(representation)")
Business_Representation(BRep_5, "Policy\nSummary\n(representation)")
Business_Representation(BRep_4, "Claim\nLetter\n(representation)")
Business_Representation(BRep_2, "Submission\nForm\n(representation)")
Business_Object(BO_8, "Claim\n(business object)")
Rel_Realization(BRep_3, BO_8, "realizes")
Rel_Aggregation(BRep_5, BRep_4, "aggregates")
Rel_Realization(BRep_2, BO_8, "realizes")
Rel_Realization(BRep_5, BCn_1, "realizes")
Rel_Aggregation(BRep_5, BRep_2, "aggregates")
Rel_Aggregation(BRep_5, BRep_3, "aggregates")
@enduml
@startuml Ex_25_BusinessCompositeElementProduct
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap08.html#_Toc489946061

title Example 25. Business Composite Element Product (Business)

Business_Service(BS_14, "Renewal\n(business service)")
Business_Service(BS_15, "Claims\nProcessing\n(business service)")
Business_Product(BPr_2, "Auto Insurance\n(product)")
Business_Service(BS_16, "Appeal\n(business service)")
Business_Product(BPr_1, "Insurance\n(product)")
Business_Contract(BCn_2, "Insurance Policy\n(contract)")
Business_Service(BS_12, "Customer\nService\n(business service)")
Business_Service(BS_17, "Drive Well\nand Save\n(business service)")
Business_Contract(BCn_3, "Drive Well and\nSave Agreement\n(contract)")
Business_Service(BS_13, "Application\n(business service)")
Rel_Aggregation(BS_12, BS_13, "aggregates")
Rel_Composition(BPr_1, BCn_2, "composed of")
Rel_Specialization(BPr_2, BPr_1, "is specialization of")
Rel_Composition(BPr_2, BCn_3, "composed of")
Rel_Aggregation(BS_12, BS_16, "aggregates")
Rel_Aggregation(BS_12, BS_15, "aggregates")
Rel_Composition(BPr_1, BS_12, "composed of")
Rel_Aggregation(BS_12, BS_14, "aggregates")
Rel_Composition(BPr_2, BS_17, "composed of")
@enduml
@startuml Ex_26_ApplicationActiveStructureElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap09.html#_Toc489946069

title Example 26. Application Active Structure Elements (Application)

Application_Component(ACmp_2, "Quotation\n(application component)")
Application_Interface(AIf_1, "Web Services\nInterface\n(application interface)")
Application_Collaboration(AC_1, "Online Travel\nInsurance Sales\n(application collaboration)")
Application_Component(ACmp_1, "Travel Website\n(application component)")
Application_Component(ACmp_3, "Purchases\n(application component)")
Rel_Composition(AC_1, AIf_1, "composed of")
Rel_Aggregation(AC_1, ACmp_2, "aggregates")
Rel_Aggregation(AC_1, ACmp_3, "aggregates")
Rel_Serving(AIf_1, ACmp_1, "serves")
@enduml
@startuml Ex_27_ApplicationBehaviorElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap09.html#_Toc489946076

title Example 27. Application Behavior Elements (Application)

Application_Function(AF_1, "Prepare\nQuotation\n(application function)")
Application_Process(AP_1, "Obtain Travel Insurance\n(application process)")
Application_Event(AE_1, "Request for\na Quotation\n(application event)")
Application_Function(AF_2, "Finalize\nPurchase\n(application function)")
Application_Service(AS_4, "Purchase Quoted\nInsurance\n(application service)")
Application_Interaction(AI_1, "PurchaseTravelInsurance\n(application interaction)")
Application_Service(AS_3, "Get Quotation\n(application service)")
Rel_Composition(AI_1, AF_1, "composed of")
Rel_Triggering(AE_1, AP_1, "triggers")
Rel_Serving(AS_4, AP_1, "serves")
Rel_Realization(AF_2, AS_4, "realizes")
Rel_Realization(AF_1, AS_3, "realizes")
Rel_Serving(AS_3, AP_1, "serves")
Rel_Composition(AI_1, AF_2, "composed of")
@enduml
@startuml Ex_28_ApplicationPassiveStructureElements
!includeurl https://raw.githubusercontent.com/smeagol74/Archimate-PlantUML/master/Archimate.puml

footer http://pubs.opengroup.org/architecture/archimate3-doc/chap09.html#_Toc489946079

title Example 28. Application Passive Structure Elements (Application)

Application_DataObject(ADO_9, "Auth Insurance\nQuotation\n(data object)")
Application_DataObject(ADO_7, "Terms and\nConditions\n(data object)")
Application_DataObject(ADO_5, "Online Insurance\nQuotation\n(data object)")
Application_DataObject(ADO_8, "Certificate of\nAuthenticity\n(data object)")
Application_DataObject(ADO_10, "Travel Insurance\nQuotation\n(data object)")
Application_DataObject(ADO_6, "Quoted\nPrice\n(data object)")
Rel_Composition(ADO_5, ADO_8, "composed of")
Rel_Specialization(ADO_10, ADO_5, "is specialization of")
Rel_Composition(ADO_5, ADO_6, "composed of")
Rel_Composition(ADO_5, ADO_7, "composed of")
Rel_Specialization(ADO_9, ADO_5, "is specialization of")
@enduml