@startuml Ex_Links
!include https://raw.githubusercontent.com/smeagol74/semod-plantuml/master/dist/semod.puml

title Example. Features: Links

Application_Interface(AIf_2, "Some interface\n(application interface)")[[https://google.com{Google main page}]]
Application_Process(AP_2, "Some Process\n(application process)")[[https://github.com]]
Application_Process(AP_3, "Another Process\n(application process)")
Rel_Association_Left(AP_2, AIf_2, "associated with")
Rel_Association_Left(AP_3, AIf_2, "associated with")
@enduml
