@startuml Ex_12_Association
!include https://raw.githubusercontent.com/smeagol74/semod-plantuml/master/dist/semod.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946003]]

title Example 12. Association (Relationships)

Business_Function(BF_2, "Policy Creation\n(business function)")
Business_Object(BO_2, "Customer File\n(business object)")
Business_Object(BO_3, "Insured Object\n(business object)")
Business_Function(Business_BusinessFunction_1, "Policy Management\n(business function)")
Business_Object(Business_BusinessObject_1, "Insurance Policy\n(business object)")
Junction_And(Junction_And_1, "(and)")
Rel_Association(Junction_And_1, BF_2, "associated with")
Rel_Association(Junction_And_1, Business_BusinessFunction_1, "associated with")
Rel_Association(Business_BusinessObject_1, BO_2, "uses >")
Rel_Association(Business_BusinessObject_1, BO_3, "uses >")
Rel_Association(Business_BusinessObject_1, Junction_And_1, "associated with")
Rel_Flow_Right(BF_2, Business_BusinessFunction_1, "Insurance Policy\n(flows to)")
@enduml
