@startuml Ex_12_Association
!include https://raw.githubusercontent.com/smeagol74/semod-plantuml/master/dist/semod.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946003]]

title Example 12. Association (Relationships)

Business_Function(BF_10, "Policy Management\n(business function)")
Business_Function(BF_11, "Policy Creation\n(business function)")
Business_Object(BO_7, "Insurance Policy\n(business object)")
Business_Object(BO_8, "Customer File\n(business object)")
Business_Object(BO_9, "Insured Object\n(business object)")
Junction_And(Junction_And_1, "(and)")
Rel_Association(Junction_And_1, BF_11, "associated with")
Rel_Association(Junction_And_1, BF_10, "associated with")
Rel_Association(BO_7, BO_8, "associated with")
Rel_Association(BO_7, BO_9, "associated with")
Rel_Flow_Right(BF_11, BF_10, "Insurance Policy\n(flows to)")
Rel_Association(BO_7, Junction_And_1, "associated with")
@enduml
