@startuml Ex_20_MeaningAndValue
!include https://raw.githubusercontent.com/smeagol74/semod-plantuml/master/dist/semod.puml

footer [[http://pubs.opengroup.org/architecture/archimate3-doc/chap06.html#_Toc489946026]]

title Example 20. Meaning and Value (Motivation)

Application_DataObject(ADO_2, "Confirmation Of\nReceipt Message\n(data object)")
Application_DataObject(ADO_3, "Review Complete\nMessage\n(data object)")
Application_DataObject(ADO_4, "Payment Complete\nMessage\n(data object)")
Application_Service(AS_2, "Push Notification\n(application service)")
Application_DataObject(Application_DataObject_1, "Message\n(data object)")
Motivation_Meaning(MM_2, "Claim Review\nComplete\n(meaning)")
Motivation_Meaning(MM_3, "Claim Has\nBeen Paid\n(meaning)")
Motivation_Stakeholder(MS_4, "Insurer\n(stakeholder)")
Motivation_Stakeholder(MS_5, "Customer\n(stakeholder)")
Motivation_Value(MV_2, "Being Informed\n(value)")
Motivation_Value(MV_3, "Peace of Mind\n(value)")
Motivation_Value(MV_4, "Certainty\n(value)")
Motivation_Meaning(Motivation_Meaning_1, "Claim Has\nBeen\nReceived\n(meaning)")
Motivation_Value(Motivation_Value_1, "Cost Efficiency\n(value)")
Rel_Access_w(AS_2, Application_DataObject_1, "writes")
Rel_Association(MS_4, Motivation_Value_1, "associated with")
Rel_Association(MS_5, MV_2, "associated with")
Rel_Association(MS_5, MV_3, "associated with")
Rel_Association(AS_2, Motivation_Value_1, "associated with")
Rel_Association(AS_2, MV_2, "associated with")
Rel_Association(AS_2, MV_3, "associated with")
Rel_Association(ADO_2, Motivation_Meaning_1, "associated with")
Rel_Association(ADO_3, MM_2, "associated with")
Rel_Association(ADO_4, MM_3, "associated with")
Rel_Composition_Down(MV_3, MV_4, "composed of")
Rel_Specialization_Up(ADO_2, Application_DataObject_1, "is specialization of")
Rel_Specialization_Up(ADO_3, Application_DataObject_1, "is specialization of")
Rel_Specialization_Up(ADO_4, Application_DataObject_1, "is specialization of")
@enduml
